apiVersion: bans.io/v1alpha1
kind: BansSlice
metadata:
  name: example-bansslice1
spec:
  # Add fields here
  snssaiList:
    - sst: 1
      sd: "010203"
  minRate: 0
  maxRate: 5
  gNBAddr: "192.168.2.11"
  tai:
    plmnId:
      mcc: "208"
      mnc: "93"
    tac: "1"
